### ISSUE TITLE
Viewer toolbar checkability changes

### ISSUE THREAD

**Issue by brechmos-stsci** [spacetelescope/cubeviz#164]
There is a bug we seemed to have introduced recently.  Go to viewer 1 and click on the zoom (magnifying glass) button and zoom the image (for example).  Then click on the Home button to resize the image to the original. This won't work, you won't be allowed to click the home button (though this functionality was or should have been working before).  In order to be allowed to click the home button you now have to *unclick* the magnifying button.

**Comment by brechmos-stsci** [comment]
Some traceback that *I think* is related to this (I was looking at the toggle whitespace):
```
    if button.isChecked() and not button.auto_uncheckable:
AttributeError: 'QAction' object has no attribute 'auto_uncheckable'
Traceback (most recent call last):
  File "/Users/crjones/miniconda3/envs/cubeviz-dev/lib/python3.6/site-packages/glue_core-0.13.0.dev4159-py3.6.egg/glue/viewers/common/qt/toolbar.py", line 114, in trigger
    self.active_tool = tool
  File "/Users/crjones/miniconda3/envs/cubeviz-dev/lib/python3.6/site-packages/glue_core-0.13.0.dev4159-py3.6.egg/glue/viewers/common/qt/toolbar.py", line 62, in active_tool
    if button.isChecked() and not button.auto_uncheckable:
AttributeError: 'QAction' object has no attribute 'auto_uncheckable'
Traceback (most recent call last):
  File "/Users/crjones/miniconda3/envs/cubeviz-dev/lib/python3.6/site-packages/glue_core-0.13.0.dev4159-py3.6.egg/glue/viewers/common/qt/toolbar.py", line 114, in trigger
    self.active_tool = tool
  File "/Users/crjones/miniconda3/envs/cubeviz-dev/lib/python3.6/site-packages/glue_core-0.13.0.dev4159-py3.6.egg/glue/viewers/common/qt/toolbar.py", line 62, in active_tool
    if button.isChecked() and not button.auto_uncheckable:
AttributeError: 'QAction' object has no attribute 'auto_uncheckable'
```

**Comment by brechmos-stsci** [comment]
Was a problem in my glue installation.  Re-created the conda environment and everything is working.
