### ISSUE TITLE
Mouseover values do not work with 2D data components

### ISSUE THREAD

**Issue by drdavella** [spacetelescope/cubeviz#404]
To reproduce, create a moment map and then hover over the leftmost image viewer. Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/dan/miniconda3/envs/cubeviz/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 388, in process
    proxy(*args, **kwargs)
  File "/Users/dan/miniconda3/envs/cubeviz/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 228, in __call__
    return mtd(*args, **kwargs)
  File "/Users/dan/stsci/glue/glue/utils/matplotlib.py", line 162, in wrapper
    result = func(*args, **kwargs)
  File "/Users/dan/stsci/cubeviz/cubeviz/image_viewer.py", line 903, in mouse_move
    arr = self.first_visible_layer().state.get_sliced_data()
  File "/Users/dan/stsci/cubeviz/cubeviz/image_viewer.py", line 134, in get_sliced_data
    return super(CubevizImageLayerState, self).get_sliced_data(view=view)
  File "/Users/dan/stsci/glue/glue/viewers/image/state.py", line 344, in get_sliced_data
    image = self._get_image(view=full_view)
  File "/Users/dan/stsci/glue/glue/viewers/image/state.py", line 462, in _get_image
    return self.layer[self.attribute, view]
  File "/Users/dan/stsci/glue/glue/core/data.py", line 931, in __getitem__
    shp = view_shape(self.shape, view)
  File "/Users/dan/stsci/glue/glue/utils/array.py", line 84, in view_shape
    return np.broadcast_to(1, shape)[view].shape
IndexError: index 1024 is out of bounds for axis 0 with size 17
```

**Comment by drdavella** [comment]
Bisect appears to point to this commit: https://github.com/spacetelescope/cubeviz/commit/0fc084648639d9ef6619ce5abd6024e6fcf9c01d
