### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by gkanarek** [spacetelescope/cubeviz#422]
I've encountered a problem in the past (and here!) where the default encoding of XQuartz on a Mac is ascii, not UTF-8. When I try to run cubeviz, I get an UnicodeDecodeError. This can be fixed with:

    $  export LC_CTYPE=en_US.utf-8

That lets cubeviz open correctly.

**Comment by gkanarek** [comment]
Sorry @drdavella, just noticed your response. Here's the traceback:
```
Traceback (most recent call last):
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/bin/cubeviz", line 7, in <module>
    from cubeviz.cubeviz import main
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/cubeviz/__init__.py", line 22, in <module>
    from . import keyboard_shortcuts
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/cubeviz/keyboard_shortcuts.py", line 7, in <module>
    from .tools.wavelengths_ui import WavelengthUI
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/cubeviz/tools/wavelengths_ui.py", line 17, in <module>
    from ..controls.wavelengths import REST_WAVELENGTH_TEXT, OBS_WAVELENGTH_TEXT
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/cubeviz/controls/wavelengths.py", line 2, in <module>
    from specviz.third_party.glue.data_viewer import dispatch as specviz_dispatch
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/specviz/__init__.py", line 28, in <module>
    linelist.populate_linelists_cache()
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/specviz/core/linelist.py", line 84, in populate_linelists_cache
    linelist = get_from_file(linelist_path, yaml_filename)
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/specviz/core/linelist.py", line 59, in get_from_file
    return LineList.read_list(linelist_fullname, loader)
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/specviz/core/linelist.py", line 226, in read_list
    col_ends = end_list)
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 327, in read
    table = fileobj.read()
  File "/Users/gkanarek/miniconda3/envs/cubeviz020/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 190: ordinal not in range(128)
```

**Comment by drdavella** [comment]
I tried to reproduce this in a Python 3.5 environment on my Mac with no luck. Can you provide any suggestions for how to reproduce?

**Comment by drdavella** [comment]
This is a problem with `specviz` and has been recorded in this issue: https://github.com/spacetelescope/specviz/issues/408.

Thanks again for the report!

**Comment by ibusko** [comment]
Specviz no longer has this issue. When running it with `LC_ALL=C` it works correctly with Unicode characters.
