### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/cubeviz#450]
Tried installing using the following command, based on advice in the documentation and the GitHub readme:
```
conda create -n cubeviz01 -c glueviz cubeviz python=3.6
```

Side issue: Doing this without specifying the python version hung, as mentioned in the AstroConda docs. If that's going to continue to be a problem, we should add the instruction to specify the python version to the cubeviz instructions. @rendinam could advise.

Then activated the environment `source activate cubeviz01` and hit a problem that was probably due to an update of glue configurations:
```(cubeviz01) ~ ❯❯❯ cubeviz
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/bin/cubeviz", line 7, in <module>
    from cubeviz.cubeviz import main
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/cubeviz/cubeviz.py", line 8, in <module>
    from glue.main import restore_session, get_splash, load_data_files, load_plugins
ImportError: cannot import name 'restore_session'
```
I just deleted my `.glue` directory, but got the same error.

I and tried starting up glue itself, getting a different error that seems like it might be related to my pyqtgraph installation? Perhaps @astrofrog could advise.:
```
(cubeviz01) ~ ❯❯❯ glue
Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
Make sure the shortcuts are NOT one of the following ['H', 'M', 'Z', 'R', 'C', 'G', 'L', 'X', 'Y', 'K', 'B', 'P']


Keyboard shortcut 'P' already registered in glue.config.viewer_tool
/Users/hcferguson/anaconda3/envs/cubeviz01/bin/pythonw: line 3:  6537 Segmentation fault: 11  /Users/hcferguson/anaconda3/envs/cubeviz01/python.app/Contents/MacOS/python "$@"
```

Went to the glueviz docs and started to work through troubleshooting advice there...
```(cubeviz01) ~ ❯❯❯ conda update -c glueviz --all```
It updated some dependencies but nothing to do with pyqtgraph and I still get the same error trying to start glue. 

But looking at the error more closely, the QTApplication thing is just a warning. It seems to be failing to load python, although if I just try to start python at the command line it works, and I can import glue without errors.
```
(cubeviz01) ~/.glue ❯❯❯ which python
/Users/hcferguson/anaconda3/envs/cubeviz01/bin/python
(cubeviz01) ~/.glue ❯❯❯ python
Python 3.6.7 | packaged by conda-forge | (default, Nov 20 2018, 18:20:05) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import glue
>>> 
```

**Comment by astrofrog** [comment]
The issue with cubeviz is due to a change in API in glue 0.14 which we need to fix in cubeviz. I think for now we should simply pin cubeviz to use <0.14. I'll update the conda package today for that.

The segmentation fault is more puzzling though - could you send me the output of ``conda list``?

**Comment by astrofrog** [comment]
@hcferguson - I've updated the conda package to now make sure that it doesn't use glue 0.14. Could you try and do ``conda update -c glueviz --all`` again to make sure cubeviz is updated and glue is downgraded? The cubeviz package should be updated to 0.2.0 build py_3.

**Comment by hcferguson** [comment]
@astrofrog Did you mean to say `conda update -c cubeviz --all` above? That did get me to the following versions:
```The following packages will be UPDATED:

    specutils:          0.2.2-py36_0  glueviz --> 0.2.2-py36_2  http://ssb.stsci.edu/astroconda
    specviz:            0.5.0-py36_1  glueviz --> 0.5.0-py36_3  cubeviz                        

The following packages will be DOWNGRADED:

    cubeviz:            0.2.1-py36_1  glueviz --> 0.2.0-py36_3  cubeviz                        
    glue-core:          0.14.1-py36_0 glueviz --> 0.13.4-py36_0 conda-forge                    
    py-expression-eval: 0.3.5-py36_0  glueviz --> 0.3.4-py36_1  cubeviz       
```
Seemed to be missing a py_expression_eval dependency...
```
(cubeviz01) ~ ❯❯❯ cubeviz
Traceback (most recent call last):
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/bin/cubeviz", line 7, in <module>
    from cubeviz.cubeviz import main
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/cubeviz/__init__.py", line 22, in <module>
    from . import keyboard_shortcuts
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/cubeviz/keyboard_shortcuts.py", line 7, in <module>
    from .tools.wavelengths_ui import WavelengthUI
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/cubeviz/tools/wavelengths_ui.py", line 17, in <module>
    from ..controls.wavelengths import REST_WAVELENGTH_TEXT, OBS_WAVELENGTH_TEXT
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/cubeviz/controls/wavelengths.py", line 2, in <module>
    from specviz.third_party.glue.data_viewer import dispatch as specviz_dispatch
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/specviz/__init__.py", line 21, in <module>
    from .interfaces.loaders import _load_yaml, _load_py
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/specviz/interfaces/__init__.py", line 1, in <module>
    from .decorators import *
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/specviz/interfaces/decorators.py", line 9, in <module>
    from ..core.data import Spectrum1DRef
  File "/Users/hcferguson/anaconda3/envs/cubeviz01/lib/python3.6/site-packages/specviz/core/data.py", line 12, in <module>
    from py_expression_eval import Parser
ModuleNotFoundError: No module named 'py_expression_eval'
```
I did a `conda install py-expression-eval` and it installed `py-expression-eval-0.3.4`. Now I get segfaults on both cubeviz and glueviz.

```
(cubeviz01) ~ ❯❯❯ cubeviz
[1]    12551 segmentation fault  cubeviz
(cubeviz01) ~ ❯❯❯ glue                                                                             ⏎
Warning: QApplication was created before pyqtgraph was imported; there may be problems (to avoid bugs, call QApplication.setGraphicsSystem("raster") before the QApplication is created).
Make sure the shortcuts are NOT one of the following ['H', 'M', 'Z', 'R', 'C', 'G', 'L', 'X', 'Y', 'K', 'B', 'P']


Keyboard shortcut 'P' already registered in glue.config.viewer_tool
/Users/hcferguson/anaconda3/envs/cubeviz01/bin/pythonw: line 3: 12606 Segmentation fault: 11  /Users/hcferguson/anaconda3/envs/cubeviz01/python.app/Contents/MacOS/python "$@"
```

**Comment by astrofrog** [comment]
Yes sorry that was the correct command. Can you send me the output of ``conda list``?

**Comment by astrofrog** [comment]
(incidentally the reason you got downgraded to cubeviz 0.2.0 is because 0.2.1 is not on PyPI and that's what I'm using the build the conda package - have opened an issue for that: https://github.com/spacetelescope/cubeviz/issues/451)

**Comment by hcferguson** [comment]
Output of conda list
```
(cubeviz01) ~ ❯❯❯ conda list                                                                       ⏎
# packages in environment at /Users/hcferguson/anaconda3/envs/cubeviz01:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0                 py36_1000    conda-forge
asdf                      2.2.1                      py_0    glueviz
asn1crypto                0.24.0                py36_1003    conda-forge
asteval                   0.9.13             pyh24bf2e0_0    glueviz
astropy                   3.0.4            py36h470a237_0    conda-forge
atomicwrites              1.2.1                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bokeh                     1.0.1                 py36_1000    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
cryptography-vectors      2.4.2                   py_1000    conda-forge
cubeviz                   0.2.0                    py36_3    cubeviz
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29             py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask                      0.20.2                     py_0    conda-forge
dask-core                 0.20.2                     py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
dill                      0.2.8.2               py36_1000    conda-forge
distributed               1.24.2                py36_1000    conda-forge
docopt                    0.6.2                      py_1    conda-forge
fast-histogram            0.5              py36h7eb728f_1    glueviz
freetype                  2.9.1                h6debe1e_4    conda-forge
glue-core                 0.13.4                   py36_0    conda-forge
h5py                      2.8.0            py36h097b052_4    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
intel-openmp              2019.1                      144  
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipython                   7.1.1           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.1                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgfortran               3.0.1                h93005f0_2  
libopenblas               0.3.3                hdc02c5d_3  
libpng                    1.6.35               ha92aebf_2    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
locket                    0.2.0                      py_2    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                3.0.2                    py36_1    conda-forge
matplotlib-base           3.0.2            py36hb2d221d_1    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
more-itertools            4.3.0                 py36_1000    conda-forge
mpl-scatter-density       0.4                        py_0    glueviz
msgpack-python            0.5.6            py36h2d50403_3    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
networkx                  2.2                        py_1    conda-forge
numpy                     1.15.4           py36h6a91979_0  
numpy-base                1.15.4           py36h8a80b8c_0  
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.3.0            py36hc736899_0    conda-forge
pip                       18.1                  py36_1000    conda-forge
plotly                    3.4.1                      py_0    conda-forge
pluggy                    0.8.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
py-expression-eval        0.3.4                    py36_1    http://ssb.stsci.edu/astroconda
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopengl                  3.1.1a1                  py36_0    http://ssb.stsci.edu/astroconda
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pyqtgraph                 0.10.0                   py36_0    http://ssb.stsci.edu/astroconda
pyrsistent                0.14.7           py36h470a237_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pytest                    4.0.0                 py36_1000    conda-forge
pytest-arraydiff          0.2                        py_0    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-doctestplus        0.1.3                      py_0    conda-forge
pytest-openfiles          0.3.0                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
python.app                1.2                    py36_200    conda-forge
pytz                      2018.7                     py_0    conda-forge
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
qt                        5.6.2               h4e759b2_10    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
radio-beam                0.2                        py_0    glueviz
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.1                py36_1000    conda-forge
retrying                  1.3.3                      py_2    conda-forge
scikit-image              0.14.1           py36hfc679d8_1    conda-forge
scipy                     1.1.0            py36h28f7352_1  
semantic_version          2.6.0                    py36_0  
setuptools                40.6.2                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
spectral-cube             0.4.3                      py_1    glueviz
specutils                 0.2.2                    py36_2    http://ssb.stsci.edu/astroconda
specviz                   0.5.0                    py36_3    cubeviz
sqlite                    3.25.3               hb1c47c0_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
xlrd                      1.1.0                      py_2    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by astrofrog** [comment]
Thanks, I'll investigate - conda forge's pyqt is frequently broken, so I'm pretty sure it will be related to that. More soon.

**Comment by astrofrog** [comment]
@hcferguson - and just to check, are you able to start up specviz?

**Comment by brechmos-stsci** [comment]
Going to close this as it appears to be a dependency issue. The dependencies will be going through some review for the next sprint and release.
