### ISSUE TITLE
Cannot start cubeviz

### ISSUE THREAD

**Issue by pierreguillard** [spacetelescope/cubeviz#595]
Hi there,

I have the folling error on startup:
$ cubeviz
/Users/guillardiap/anaconda3/envs/cubeviz030/lib/python3.7/site-packages/glue/external/echo/__init__.py:3: UserWarning: glue.external.echo is deprecated, import from echo directly instead
  warnings.warn('glue.external.echo is deprecated, import from echo directly instead')
Traceback (most recent call last):
  File "/Users/guillardiap/anaconda3/envs/cubeviz030/bin/cubeviz", line 5, in <module>
    from cubeviz.cubeviz import main
  File "/Users/guillardiap/anaconda3/envs/cubeviz030/lib/python3.7/site-packages/cubeviz/cubeviz.py", line 20, in <module>
    from .data_factories import DataFactoryConfiguration
  File "/Users/guillardiap/anaconda3/envs/cubeviz030/lib/python3.7/site-packages/cubeviz/data_factories/__init__.py", line 17, in <module>
    from ..listener import CUBEVIZ_LAYOUT
  File "/Users/guillardiap/anaconda3/envs/cubeviz030/lib/python3.7/site-packages/cubeviz/listener.py", line 7, in <module>
    from .layout import CubeVizLayout
  File "/Users/guillardiap/anaconda3/envs/cubeviz030/lib/python3.7/site-packages/cubeviz/layout.py", line 12, in <module>
    from glue.external.echo.qt.connect import (UserDataWrapper, _find_combo_data,
ImportError: cannot import name '_find_combo_text' from 'glue.external.echo.qt.connect' (/Users/guillardiap/anaconda3/envs/cubeviz030/lib/python3.7/site-packages/glue/external/echo/qt/connect.py)

Any ideas?

OSX 10.13.6
conda 4.9.1

**Comment by MTLeist255** [comment]
I am also having the same error code, and have the same environment running OSC and conda

**Comment by orifox** [comment]
If you can, please submit a ticket to the JWST help desk for a faster response: jwsthelp.stsci.edu
